# เปิดใช้งาน IPC Server ถาวร (เพื่อให้ไฟล์ .bat ยิงลิงก์เข้ามาได้ตลอดเวลา)
input-ipc-server=\\.\pipe\mpvsocket

# แนะนำเพิ่มเติม: ให้ mpv จำตำแหน่งล่าสุดที่เล่นค้างไว้
save-position-on-quit=no

# แนะนำเพิ่มเติม: เปิดใช้งาน Hardware Acceleration (ใช้ GPU ช่วยถอดรหัส ภาพลื่นและประหยัด CPU)
hwdec=auto